# Generated by Django 2.1.11 on 2019-08-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingreduent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingreduent',
            new_name='Ingredient',
        ),
    ]
